//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ..\ChessBot\AlgebraicNotation\AlgebraicNotation.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ChessBot.AlgebraicNotation {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAlgebraicNotationListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class AlgebraicNotationBaseListener : IAlgebraicNotationListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AlgebraicNotationParser.move"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMove([NotNull] AlgebraicNotationParser.MoveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AlgebraicNotationParser.move"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMove([NotNull] AlgebraicNotationParser.MoveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AlgebraicNotationParser.moveDesc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveDesc([NotNull] AlgebraicNotationParser.MoveDescContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AlgebraicNotationParser.moveDesc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveDesc([NotNull] AlgebraicNotationParser.MoveDescContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AlgebraicNotationParser.ordinaryMoveDesc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrdinaryMoveDesc([NotNull] AlgebraicNotationParser.OrdinaryMoveDescContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AlgebraicNotationParser.ordinaryMoveDesc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrdinaryMoveDesc([NotNull] AlgebraicNotationParser.OrdinaryMoveDescContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AlgebraicNotationParser.square"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSquare([NotNull] AlgebraicNotationParser.SquareContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AlgebraicNotationParser.square"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSquare([NotNull] AlgebraicNotationParser.SquareContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AlgebraicNotationParser.pieceKind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPieceKind([NotNull] AlgebraicNotationParser.PieceKindContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AlgebraicNotationParser.pieceKind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPieceKind([NotNull] AlgebraicNotationParser.PieceKindContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AlgebraicNotationParser.source"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSource([NotNull] AlgebraicNotationParser.SourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AlgebraicNotationParser.source"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSource([NotNull] AlgebraicNotationParser.SourceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AlgebraicNotationParser.destination"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDestination([NotNull] AlgebraicNotationParser.DestinationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AlgebraicNotationParser.destination"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDestination([NotNull] AlgebraicNotationParser.DestinationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AlgebraicNotationParser.promotionKind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPromotionKind([NotNull] AlgebraicNotationParser.PromotionKindContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AlgebraicNotationParser.promotionKind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPromotionKind([NotNull] AlgebraicNotationParser.PromotionKindContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AlgebraicNotationParser.status"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatus([NotNull] AlgebraicNotationParser.StatusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AlgebraicNotationParser.status"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatus([NotNull] AlgebraicNotationParser.StatusContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace ChessBot.AlgebraicNotation
